"""Platform definition data for URL routing and DOM selectors.

This module contains the platform definitions and unmapped host mappings,
split from platform_catalog.py to keep each module under the 500-line limit.
"""
from __future__ import annotations
from collections.abc import Mapping

from src.crawler.platform_types import ExtractorFamily, PlatformDefinition, _selectors
from src.crawler.platform_wechat_data import (
    WECHAT_VIDEO_INCLUDE_PATTERNS,
    WECHAT_VIDEO_SELECTORS,
)

# These public sites appeared in field tests, but the immutable workbook has no
# truthful platform enum for them. Keep the distinction explicit so callers can
# explain why they are not auto-routed instead of disguising them as UC/360/etc.
UNMAPPED_TEMPLATE_HOSTS: Mapping[str, str] = {
    "smzdm.com": "什么值得买",
    "dazhe.com": "打折网",
    "chinadaily.com.cn": "中国日报",
}


PLATFORM_DEFINITIONS: tuple[PlatformDefinition, ...] = (
    PlatformDefinition(
        "douyin_ecommerce",
        "电商平台",
        "字节跳动_抖音_电商平台",
        ExtractorFamily.COMMERCE,
        ("haohuo.jinritemai.com", "jinritemai.com", "douyin.com"),
        _selectors(
            title=("[data-e2e='product-title']", "h1"),
            content_text=("[data-e2e='product-desc']", ".product-detail"),
            store_name=("[data-e2e='shop-name']", ".shop-name"),
            author_url=("[data-e2e='shop-name'] a", "a[data-e2e='shop-name']", ".shop-name a"),
        ),
        include_patterns=(r"/product", r"product_id=", r"/views/product", r"/ecommerce/trade/detail/"),
        manual_only=True,
    ),
    PlatformDefinition(
        "xianyu",
        "电商平台",
        "阿里_闲鱼_电商平台",
        ExtractorFamily.COMMERCE,
        ("goofish.com", "2.taobao.com"),
        _selectors(
            title=("h1", ".item-title", "[class*='itemTitle']", "[class*='title']"),
            content_text=(".item-desc", ".desc", "[class*='itemDesc']", "[class*='description']"),
            store_name=(
                ".seller-name",
                "[class*='sellerName']",
                "[class*='userName']",
                "[class*='nickname']",
            ),
            author_name=(
                ".seller-name",
                "[class*='sellerName']",
                "[class*='userName']",
                "[class*='nickname']",
            ),
            author_url=(
                ".seller-name a",
                "a[class*='seller']",
                ".user-info a",
                "a[href*='/personal']",
            ),
        ),
        include_patterns=(r"/item", r"id="),
    ),
    PlatformDefinition(
        "tmall",
        "电商平台",
        "阿里_天猫_电商平台",
        ExtractorFamily.COMMERCE,
        ("tmall.com",),
        _selectors(
            title=("h1", ".tb-detail-hd", "[class*='ItemTitle']"),
            content_text=(".tm-fcs-panel", ".detail-content", "[class*='ItemDesc']"),
            store_name=(
                ".slogo-shopname",
                ".shop-name",
                "[class*='shopName']",
                "[class*='ShopHeader--title']",
            ),
            author_url=(
                ".slogo a",
                "a.slogo-shopname",
                ".slogo-shopname a",
                "a[class*='shop']",
            ),
        ),
        include_patterns=(r"/item\.htm", r"id="),
    ),
    PlatformDefinition(
        "taobao",
        "电商平台",
        "阿里_淘宝_电商平台",
        ExtractorFamily.COMMERCE,
        ("taobao.com",),
        _selectors(
            title=("h1", ".ItemTitle--mainTitle", "[class*='ItemTitle--mainTitle']"),
            content_text=(".ItemDesc--content", ".detail-content", "[class*='ItemDesc--content']"),
            store_name=(
                ".ShopHeader--title",
                "[class*='ShopHeader--title']",
                ".tb-shop-name",
                ".shop-name",
                "[class*='shopName']",
            ),
            author_url=(
                ".ShopHeader--title a",
                "a[class*='ShopHeader']",
                ".shop-name a",
                "a[href*='shop']",
            ),
        ),
        include_patterns=(r"/item\.htm", r"id="),
    ),
    PlatformDefinition(
        "1688",
        "电商平台",
        "阿里_1688_电商平台",
        ExtractorFamily.COMMERCE,
        ("1688.com",),
        _selectors(
            title=("h1", ".title-text", "[class*='title-text']"),
            content_text=(".detail-content", "[class*='detail-content']"),
            store_name=(
                ".company-name",
                ".shop-name",
                ".shop-company-name",
                "[class*='company-name']",
                "[class*='companyName']",
            ),
            author_url=(
                ".company-name a",
                ".shop-name a",
                "a[class*='company']",
                "a[href*='company']",
            ),
        ),
        include_patterns=(r"/offer/",),
    ),
    PlatformDefinition(
        "jd",
        "电商平台",
        "京东_京东商城_电商平台",
        ExtractorFamily.COMMERCE,
        ("jd.com",),
        _selectors(
            title=(".sku-name", "h1", "[class*='sku-name']"),
            content_text=(".detail-content", "#detail", "[class*='detail-content']"),
            store_name=(
                "#popbox .name a",
                ".J-hove-wrap .name a",
                ".name a",
                ".shop-name",
                "[class*='shopName']",
            ),
            author_url=(
                "#popbox .name a",
                ".J-hove-wrap .name a",
                ".name a",
                ".shop-name a",
            ),
        ),
        include_patterns=(r"/\d+\.html", r"/item/", r"sku="),
    ),
    PlatformDefinition(
        "pinduoduo",
        "电商平台",
        "拼多多",
        ExtractorFamily.COMMERCE,
        ("pinduoduo.com", "yangkeduo.com"),
        _selectors(
            title=("h1", "[class*='goodsName']", "[class*='goods-name']"),
            content_text=("[class*='goodsDesc']", "[class*='goods-desc']", "main"),
            store_name=(
                "[class*='mallName']",
                "[class*='mall-name']",
                "[class*='storeName']",
                "[class*='shopName']",
            ),
            author_url=(
                "[class*='mallName'] a",
                "a[class*='mall']",
                "a[href*='mall_id']",
            ),
        ),
        include_patterns=(r"/goods", r"goods_id="),
    ),
    PlatformDefinition(
        "wechat_official",
        "公众号",
        "微信-公众号",
        ExtractorFamily.ARTICLE,
        ("mp.weixin.qq.com",),
        _selectors(
            title=("#activity-name", "h1"),
            content_text=("#js_content", "article"),
            author_name=("#js_name", ".account_nickname_inner"),
            author_id=(".account_meta_value",),
            published_at=("#publish_time", "em#publish_time"),
        ),
        include_patterns=(r"/s(?:/|$|\?)", r"__biz=", r"sn="),
    ),
    PlatformDefinition(
        "baijiahao",
        "公众号",
        "百度_百家号_公众号",
        ExtractorFamily.ARTICLE,
        ("baijiahao.baidu.com", "mbd.baidu.com"),
        _selectors(
            title=(
                ".article-title",
                "h1",
                "[class*='articleTitle']",
                "[class*='detail-title']",
                "[class*='hot-title']",
            ),
            content_text=(
                ".article-content",
                "article",
                "[class*='articleContent']",
                "[class*='hot-detail']",
                "main",
            ),
            author_name=(".author-name", "[class*='authorName']"),
            author_url=(".author-name a", "[class*='author'] a"),
            published_at=(".date", "time", "[class*='publishTime']"),
        ),
        include_patterns=(
            r"/s(?:/|$|\?)",
            r"id=",
            r"/builder/na/hot/detail",
            r"/newspage/data/(?:videolanding|landingshare)",
        ),
    ),
    PlatformDefinition(
        "wechat_video",
        "图文视频",
        "腾讯_微信_图文视频",
        ExtractorFamily.SOCIAL,
        ("channels.weixin.qq.com", "weixin.qq.com"),
        WECHAT_VIDEO_SELECTORS,
        include_patterns=WECHAT_VIDEO_INCLUDE_PATTERNS,
    ),
    PlatformDefinition(
        "sohu_video",
        "图文视频",
        "搜狐_搜狐视频_图文视频",
        ExtractorFamily.SOCIAL,
        ("tv.sohu.com",),
        _selectors(title=("h1", ".video-title"), content_text=(".video-info", "main"), author_name=(".user-name",), author_url=(".user-name a",), published_at=("time", "[class*='time']", "[class*='date']")),
        include_patterns=(r"/v/",),
    ),
    PlatformDefinition(
        "xiaohongshu",
        "图文视频",
        "行吟科技_小红书_图文视频",
        ExtractorFamily.SOCIAL,
        ("xiaohongshu.com", "xhslink.com"),
        _selectors(
            title=(".note-content .title", "#detail-title"),
            content_text=(".note-content .desc", "#detail-desc"),
            author_name=(".author-wrapper .name", ".username"),
            author_url=(".author-wrapper a",),
            published_at=(".date", ".publish-time"),
        ),
        include_patterns=(r"/explore/[^/?#]+", r"/discovery/item/", r"/helper/detail/", r"/help/detail"),
    ),
    PlatformDefinition(
        "douyin",
        "图文视频",
        "字节跳动_抖音_图文视频",
        ExtractorFamily.SOCIAL,
        ("douyin.com", "iesdouyin.com"),
        _selectors(
            content_text=(
                "[data-e2e='video-desc']",
                "[data-e2e='browse-video-desc']",
                ".author-container + .desc",
                ".desc",
            ),
            author_name=(
                "[data-e2e='video-author-name']",
                "[data-e2e='browse-username']",
                ".author-container .author-name",
            ),
            author_url=("[data-e2e='video-author-name'] a",),
            published_at=("[data-e2e='video-publish-time']",),
        ),
        exclude_patterns=(r"/product", r"product_id=", r"/views/product", r"/ecommerce/trade/detail/"),
    ),
    PlatformDefinition(
        "kuaishou",
        "图文视频",
        "快手科技_快手_图文视频",
        ExtractorFamily.SOCIAL,
        ("kuaishou.com", "gifshow.com"),
        _selectors(
            content_text=(
                ".video-info-title",
                ".caption",
                ".work-info .desc",
                "[class*='work-info'] [class*='desc']",
            ),
            author_name=(
                ".profile-user-name",
                ".author-name",
                ".work-info .author .txt",
            ),
            author_url=(
                ".profile-user-name a",
                "[class*='author'] a",
                "a[href*='/profile/']",
            ),
            published_at=(".publish-time",),
        ),
        include_patterns=(r"/short-video/", r"/fw/photo/"),
    ),
    PlatformDefinition(
        "bilibili",
        "图文视频",
        "幻电科技_哔哩哔哩_图文视频",
        ExtractorFamily.SOCIAL,
        ("bilibili.com", "b23.tv"),
        _selectors(title=("h1.video-title", "h1"), content_text=(".video-desc-container", ".opus-module-content"), author_name=(".up-name", ".bili-user-profile-name"), author_url=(".up-name", ".up-info-container a")),
        include_patterns=(r"/video/", r"/opus/", r"^/[A-Za-z0-9]+/?$"),
    ),
    PlatformDefinition(
        "tudou",
        "图文视频",
        "阿里巴巴_土豆_图文视频",
        ExtractorFamily.SOCIAL,
        ("tudou.com",),
        _selectors(title=("h1", ".title"), content_text=("main", ".content"), author_name=("[class*='author']", ".user-name"), published_at=("time", "[class*='time']", "[class*='date']")),
        include_patterns=(r"/programs/view/", r"/v_show/"),
    ),
    PlatformDefinition(
        "youku",
        "图文视频",
        "阿里巴巴_优酷_图文视频",
        ExtractorFamily.SOCIAL,
        ("youku.com",),
        _selectors(title=("h1", ".title"), content_text=("main", ".content"), author_name=("[class*='author']", ".user-name"), author_url=("[class*='author'] a", "a[href*='/user/']"), published_at=("time", "[class*='time']", "[class*='date']")),
        include_patterns=(r"/v_show/",),
    ),
    PlatformDefinition(
        "ixigua",
        "图文视频",
        "字节跳动_西瓜视频_图文视频",
        ExtractorFamily.SOCIAL,
        ("ixigua.com",),
        _selectors(title=("h1", ".title", "[class*='title']"), content_text=("main", ".content", "article"), author_name=("[class*='author']", "[class*='name']"), author_url=("[class*='author'] a", "[class*='avatar'] a"), published_at=("time", "[class*='time']", "[class*='date']")),
        include_patterns=(r"/video/", r"/\d{10,}"),
    ),
    PlatformDefinition(
        "iqiyi",
        "图文视频",
        "爱奇艺_爱奇艺_图文视频",
        ExtractorFamily.SOCIAL,
        ("iqiyi.com",),
        _selectors(title=("h1", ".title", "[class*='title']"), content_text=("main", ".content", "article"), author_name=("[class*='author']", ".user-name", "[class*='name']"), author_url=("[class*='author'] a", "[class*='avatar'] a"), published_at=("time", "[class*='time']", "[class*='date']")),
        include_patterns=(r"/v_", r"/w_"),
    ),
    PlatformDefinition(
        "weibo",
        "微博博客",
        "新浪_新浪微博_博客贴吧",
        ExtractorFamily.SOCIAL,
        ("weibo.com", "weibo.cn"),
        _selectors(content_text=("[class*='detail_wbtext']", "[node-type='feed_list_content']"), author_name=("[class*='head_name']", ".username"), author_url=("[class*='head_name'] a",), published_at=("time", "[class*='time']")),
        include_patterns=(r"/\d+/", r"/detail/"),
    ),
    PlatformDefinition(
        "tieba",
        "微博博客",
        "百度_百度贴吧_博客贴吧",
        ExtractorFamily.SOCIAL,
        ("tieba.baidu.com",),
        _selectors(title=(".core_title_txt", "h1"), content_text=(".d_post_content", ".threadlist_abs"), author_name=(".p_author_name", ".frs-author-name"), author_url=("a.p_author_name", ".p_author_name a", "a.frs-author-name", "a[href*='/home/main?un=']"), published_at=(".tail-info",)),
        include_patterns=(r"/p/\d+",),
    ),
    PlatformDefinition(
        "zhihu",
        "微博博客",
        "知乎_知乎_博客贴吧",
        ExtractorFamily.SOCIAL,
        ("zhihu.com",),
        _selectors(title=(".Post-Title", ".QuestionHeader-title"), content_text=(".RichContent-inner", "article"), author_name=(".AuthorInfo-name", ".UserLink-link"), author_url=(".AuthorInfo-name a", ".UserLink-link"), published_at=(".ContentItem-time", "time")),
        include_patterns=(r"/question/", r"/p/", r"/answer/", r"/zvideo/"),
    ),
    PlatformDefinition(
        "toutiao",
        "生活资讯",
        "字节跳动_今日头条_生活资讯",
        ExtractorFamily.ARTICLE,
        ("toutiao.com",),
        _selectors(
            title=("h1", ".article-title"),
            content_text=("article", ".article-content", ".syl-article-base"),
            author_name=("[class*='author']", ".source"),
            author_url=("[class*='author'] a", ".source a", "a[href*='/c/']"),
            published_at=("time", "[class*='time']", "[class*='date']"),
        ),
        include_patterns=(r"/article/",),
    ),
    PlatformDefinition(
        "netease_news",
        "生活资讯",
        "网易_网易新闻_生活资讯",
        ExtractorFamily.ARTICLE,
        ("163.com",),
        _selectors(
            title=("h1", ".post_title"),
            content_text=("#content", ".post_body"),
            author_name=(".post_info", ".source"),
            author_url=(".post_info a", ".source a"),
            published_at=(".post_info", ".post_time_source", "time", "[class*='time']", "[class*='date']"),
        ),
        include_patterns=(r"/dy/article/", r"/article/", r"/\d{2}/\d{4}/"),
    ),
    PlatformDefinition(
        "ifeng_news",
        "生活资讯",
        "凤凰网_凤凰新闻_生活资讯",
        ExtractorFamily.ARTICLE,
        ("ifeng.com",),
        _selectors(
            title=("h1", ".article-title"),
            content_text=("#main_content", "#articleBox", ".article-content"),
            author_name=(".source", "[class*='source']"),
            author_url=(".source a", "[class*='source'] a"),
            published_at=("time", "[class*='time']"),
        ),
        include_patterns=(r"/c/",),
    ),
    PlatformDefinition("huyou", "生活资讯", "搜狐_狐友_生活资讯", ExtractorFamily.SOCIAL, ("huyou.sohu.com", "w.sohu.com", "h5-ol.sns.sohu.com"), _selectors(author_name=("[class*='name']", ".username"), author_url=("[class*='name'] a", "[class*='avatar'] a"), published_at=("time", "[class*='time']", "[class*='date']")), include_patterns=(r"/hy-super-h5/share/",)),
    PlatformDefinition(
        "sohu_news",
        "生活资讯",
        "搜狐_搜狐新闻_生活资讯",
        ExtractorFamily.ARTICLE,
        ("sohu.com",),
        _selectors(
            title=("h1", ".text-title", ".article-title"),
            content_text=("article", ".article-content", "#mp-editor", ".text"),
            author_name=(".author-name", ".source", "[class*='source']"),
            author_url=(".author-name a", "[class*='source'] a"),
            published_at=(".article-info .time", "#news-time", "time", "[class*='time']"),
        ),
        include_patterns=(r"/a/",),
        exclude_patterns=(r"/video",),
    ),
    PlatformDefinition(
        "hupu",
        "生活资讯",
        "虎扑_虎扑_生活资讯",
        ExtractorFamily.SOCIAL,
        ("hupu.com",),
        _selectors(
            title=("h1", "[class*='title']"),
            content_text=("article", "main", ".content", "[class*='content']"),
            author_name=("[class*='author']", ".user-name", "[class*='name']"),
            author_url=("[class*='author'] a", "[class*='avatar'] a", "a[href*='/u/']", "a[href*='/profile/']"),
            published_at=("time", "[class*='time']", "[class*='date']", "[class*='timestamp']"),
        ),
        include_patterns=(r"/bbs/", r"/\d+(?:-\d+)?(?:\.html)?$"),
    ),
    PlatformDefinition("meituan", "生活资讯", "三快_美团_生活资讯", ExtractorFamily.COMMERCE, ("meituan.com", "dianping.com"), _selectors(title=("h1", ".title"), content_text=("main", ".content"), store_name=(".shop-name",), published_at=("time", "[class*='time']", "[class*='date']")), include_patterns=(r"/news/", r"/review/", r"/shop/", r"/meishi/")),
    PlatformDefinition(
        "dongchedi",
        "生活资讯",
        "字节跳动_懂车帝_生活资讯",
        ExtractorFamily.ARTICLE,
        ("dongchedi.com",),
        _selectors(
            title=("h1", ".title", "[class*='title']"),
            content_text=("article", "main", ".content", "[class*='content']"),
            author_name=("[class*='author']", ".source", "[class*='name']"),
            author_url=("[class*='author'] a", "[class*='avatar'] a", "a[href*='/user/']"),
            published_at=("time", "[class*='time']", "[class*='date']"),
        ),
        include_patterns=(r"/article/", r"/ugc/", r"/video/\d+"),
    ),
    PlatformDefinition("uc_browser", "浏览器", "阿里巴巴_UC浏览器_浏览器", ExtractorFamily.ARTICLE, ("sm.cn", "uc.cn"), _selectors(title=("h1", ".title"), content_text=("article", "main"), published_at=("time", "[class*='time']", "[class*='date']")), include_patterns=(r"/article/", r"/service", r"/about", r"/help/", r"/detail")),
    PlatformDefinition("browser_360", "浏览器", "360_360浏览器_浏览器", ExtractorFamily.ARTICLE, ("so.com", "360kuai.com", "browser.360.cn"), _selectors(title=("h1", ".title"), content_text=("article", "main"), published_at=("time", "[class*='time']", "[class*='date']")), include_patterns=(r"/article/", r"/detail", r"/se/help/", r"faq-detail")),
    PlatformDefinition(
        "huawei_browser",
        "浏览器",
        "华为_华为浏览器_浏览器",
        ExtractorFamily.ARTICLE,
        ("browser.huawei.com", "consumer.huawei.com"),
        _selectors(title=("h1", ".title"), content_text=("article", "main", ".content"), published_at=("time", "[class*='time']", "[class*='date']")),
        include_patterns=(r"/support/content/",),
    ),
    PlatformDefinition("qq_browser", "浏览器", "腾讯_QQ浏览器_浏览器", ExtractorFamily.ARTICLE, ("browser.qq.com", "mb.qq.com"), _selectors(title=("h1", ".title"), content_text=("article", "main"), published_at=("time", "[class*='time']", "[class*='date']")), include_patterns=(r"/materials/", r"/license", r"/support", r"/faq")),
)
